Add AsyncQuidax class
gray-adeyi/pyquidax pull request #35
Opened 2023-12-30 00:59 UTC by beekaz

This resolves #9

2023-12-30 01:15 UTC, gray-adeyi requested changes

2023-12-30 01:15 UTC, gray-adeyi commented on pyquidax/quidax.py
>  class AsyncQuidax:
Blessing it's not just about coping and pasting. I want you to understand why we do what we do. This issue is about implementing AsyncQuidax you've already seen an empty class defined so why create a new one with the same name

2023-12-30 01:15 UTC, gray-adeyi commented on pyquidax/quidax.py
> +class AsyncQuidax:
This too. Do we really need it?

2024-01-01 23:56 UTC, gray-adeyi commented
Click on the resolve conversation button for the requested changes you've made

2024-01-02 00:20 UTC, gray-adeyi commented
I wrote review comments for you to make some corrections. for the ones you've fixed click on the `resolve conversation` button

2024-01-02 00:34 UTC, beekaz reviewed
resolves #9

2024-01-03 06:20 UTC, gray-adeyi commented
Nicely done 👍🏿

2024-01-03 06:20 UTC, merged